export const state=()=>({
  orderQuantity:[],
  prefinancesQuantity:[],
  prefinancesCreator:[],
  genderReport:[],
  countryReport:[],
  clientReport:[],
  managerReport:[],
})

export const getters={
  orderQuantity:(state)=>state.orderQuantity,
  prefinancesQuantity:(state)=>state.prefinancesQuantity,
  prefinancesCreator:(state)=>state.prefinancesCreator,
  genderReport:(state)=>state.genderReport,
  countryReport:(state)=>state.countryReport,
  clientReport:(state)=>state.clientReport,
  managerReport:(state)=>state.managerReport,
}

export const mutations={
  setOrderQuantity(state,item){
    state.orderQuantity=item
  },
  setPrefinancesQuantity(state,item){
    state.prefinancesQuantity=item
  },
  setPrefinancesCreator(state,item){
    state.prefinancesCreator=item
  },
  setGenderReport(state,item){
    state.genderReport=item
  },
  setCountryReport(state,item){
    state.countryReport=item
  },
  setClientReport(state,item){
    state.clientReport=item
  },
  setManagerReport(state,item){
    state.managerReport=item
  },
}

export const actions={
  getOrderQuantity({commit},date){
    this.$axios.get(`/api/v1/report/model/order/quantity?date=${date}`)
    .then((res)=>{
      commit("setOrderQuantity",res.data.data)
    })
    .catch((response)=>{
      console.log(response);
    })
  },
  getPrefinancesQuantity({commit},date){
    this.$axios.get(`/api/v1/report/pre-finance/quantity?date=${date}`)
    .then((res)=>{
      commit("setPrefinancesQuantity",res.data.data)
    })
    .catch((response)=>{
      console.log(response);
    })
  },
  getPrefinancesCreators({commit},date){
    this.$axios.get(`/api/v1/report/pre-finance/creator?date=${date}`)
    .then((res)=>{
      commit("setPrefinancesCreator",res.data.data)
    })
    .catch((response)=>{
      console.log(response);
    })
  },
  getReportGender({commit},date){
    this.$axios.get(`/api/v1/report/model/gender?date=${date}`)
    .then((res)=>{
      commit("setGenderReport",res.data.data)
    })
    .catch((response)=>{
      console.log(response);
    })
  },
  getReportCountry({commit},date){
    this.$axios.get(`/api/v1/report/order/country?date=${date}`)
    .then((res)=>{
      commit("setCountryReport",res.data.data)
    })
    .catch((response)=>{
      console.log(response);
    })
  },
  getReportClinet({commit},date){
    this.$axios.get(`/api/v1/report/order/client?date=${date}`)
    .then((res)=>{
      commit("setClientReport",res.data.data)
    })
    .catch((response)=>{
      console.log(response);
    })
  },
  getReportManager({commit},date){
    this.$axios.get(`/api/v1/report/order/manager?date=${date}`)
    .then((res)=>{
      commit("setManagerReport",res.data.data)
    })
    .catch((response)=>{
      console.log(response);
    })
  },
}